- name: Scrumble deployment
  hosts: all
  sudo: true
  tasks:
    - name: proxy
      docker:
        name: proxy
        image: jwilder/nginx-proxy
        state: started
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
          - "80:80"

    - name: data container
      docker:
        name: scrumbledata
        image: busybox
        state: started
        volumes:
          - /data

    - name: postgres container
      docker:
        name: scrumbledatabase
        image: postgres:9.4
        volumes_from:
          - scrumbledata
        ports:
          - "5431:5432"
        state: started

    - name: api container
      docker:
        name: scrumbleapi
        image: nicgirault/scrumble-api
        volumes_from:
          - scrumbledata
        ports:
          - "8082:8000"
        state: reloaded
        pull: always
        links:
          - scrumbledatabase
        env:
          DB_DATABASE: postgres
          DB_USERNAME: postgres

    - name: client container
      docker:
        name: scrumbleclient
        image: nicgirault/scrumble
        ports:
          - "8083:80"
        state: started
        pull: always
        env:
          VIRTUAL_HOST: app.scrumble.io

    - name: showcase container
      docker:
        name: showcase
        image: nicgirault/scrumble-showcase
        ports:
          - "8080:80"
        state: started
        pull: always
        env:
          VIRTUAL_HOST: scrumble.io
