appbuilder:
  image: node:wheezy
  volumes:
    - ./client:/app
  working_dir: /app
  environment:
    API_URL: "https://api.scrumble.io/v1"
    GOOGLE_CLIENT_ID: '605908567890-3bg3dmamghq5gd7i9sqsdhvoflef0qku.apps.googleusercontent.com'
  command: "npm run build"
